version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"  
    schedule:
      interval: "daily" 
    open-pull-requests-limit: 100
    reviewers:
      - "your-github-username" 
    labels:
      - "dependencies" 
    ignore:
      - dependency-name: "next"
        versions: ["13.x"] 
